// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: cache_cdc.proto

package cdcwire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RowChange_Operation int32

const (
	RowChange_OPERATION_UNSPECIFIED RowChange_Operation = 0
	RowChange_OPERATION_INSERT      RowChange_Operation = 1
	RowChange_OPERATION_UPDATE      RowChange_Operation = 2
	RowChange_OPERATION_DELETE      RowChange_Operation = 3
)

// Enum value maps for RowChange_Operation.
var (
	RowChange_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_INSERT",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	RowChange_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_INSERT":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x RowChange_Operation) Enum() *RowChange_Operation {
	p := new(RowChange_Operation)
	*p = x
	return p
}

func (x RowChange_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RowChange_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_cdc_proto_enumTypes[0].Descriptor()
}

func (RowChange_Operation) Type() protoreflect.EnumType {
	return &file_cache_cdc_proto_enumTypes[0]
}

func (x RowChange_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RowChange_Operation.Descriptor instead.
func (RowChange_Operation) EnumDescriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{1, 0}
}

type ClosedBoundary_Mode int32

const (
	ClosedBoundary_MODE_UNSPECIFIED          ClosedBoundary_Mode = 0
	ClosedBoundary_MODE_FENCED               ClosedBoundary_Mode = 1
	ClosedBoundary_MODE_MANAGED_INVALIDATION ClosedBoundary_Mode = 2
)

// Enum value maps for ClosedBoundary_Mode.
var (
	ClosedBoundary_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_FENCED",
		2: "MODE_MANAGED_INVALIDATION",
	}
	ClosedBoundary_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":          0,
		"MODE_FENCED":               1,
		"MODE_MANAGED_INVALIDATION": 2,
	}
)

func (x ClosedBoundary_Mode) Enum() *ClosedBoundary_Mode {
	p := new(ClosedBoundary_Mode)
	*p = x
	return p
}

func (x ClosedBoundary_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClosedBoundary_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_cdc_proto_enumTypes[1].Descriptor()
}

func (ClosedBoundary_Mode) Type() protoreflect.EnumType {
	return &file_cache_cdc_proto_enumTypes[1]
}

func (x ClosedBoundary_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClosedBoundary_Mode.Descriptor instead.
func (ClosedBoundary_Mode) EnumDescriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{2, 0}
}

// First message in this file: Confluent Protobuf message-index path [0].
type CacheCdcRecord struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Version     uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SourceEpoch string                 `protobuf:"bytes,2,opt,name=source_epoch,json=sourceEpoch,proto3" json:"source_epoch,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*CacheCdcRecord_Change
	//	*CacheCdcRecord_Boundary
	Body          isCacheCdcRecord_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheCdcRecord) Reset() {
	*x = CacheCdcRecord{}
	mi := &file_cache_cdc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheCdcRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheCdcRecord) ProtoMessage() {}

func (x *CacheCdcRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheCdcRecord.ProtoReflect.Descriptor instead.
func (*CacheCdcRecord) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{0}
}

func (x *CacheCdcRecord) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CacheCdcRecord) GetSourceEpoch() string {
	if x != nil {
		return x.SourceEpoch
	}
	return ""
}

func (x *CacheCdcRecord) GetBody() isCacheCdcRecord_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CacheCdcRecord) GetChange() *RowChange {
	if x != nil {
		if x, ok := x.Body.(*CacheCdcRecord_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *CacheCdcRecord) GetBoundary() *ClosedBoundary {
	if x != nil {
		if x, ok := x.Body.(*CacheCdcRecord_Boundary); ok {
			return x.Boundary
		}
	}
	return nil
}

type isCacheCdcRecord_Body interface {
	isCacheCdcRecord_Body()
}

type CacheCdcRecord_Change struct {
	Change *RowChange `protobuf:"bytes,3,opt,name=change,proto3,oneof"`
}

type CacheCdcRecord_Boundary struct {
	Boundary *ClosedBoundary `protobuf:"bytes,4,opt,name=boundary,proto3,oneof"`
}

func (*CacheCdcRecord_Change) isCacheCdcRecord_Body() {}

func (*CacheCdcRecord_Boundary) isCacheCdcRecord_Body() {}

type RowChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Operation     RowChange_Operation    `protobuf:"varint,4,opt,name=operation,proto3,enum=cdc.RowChange_Operation" json:"operation,omitempty"`
	Before        *RowImage              `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`
	After         *RowImage              `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowChange) Reset() {
	*x = RowChange{}
	mi := &file_cache_cdc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowChange) ProtoMessage() {}

func (x *RowChange) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowChange.ProtoReflect.Descriptor instead.
func (*RowChange) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{1}
}

func (x *RowChange) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *RowChange) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *RowChange) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RowChange) GetOperation() RowChange_Operation {
	if x != nil {
		return x.Operation
	}
	return RowChange_OPERATION_UNSPECIFIED
}

func (x *RowChange) GetBefore() *RowImage {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *RowChange) GetAfter() *RowImage {
	if x != nil {
		return x.After
	}
	return nil
}

type ClosedBoundary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommittedBefore *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=committed_before,json=committedBefore,proto3" json:"committed_before,omitempty"`
	Mode            ClosedBoundary_Mode    `protobuf:"varint,2,opt,name=mode,proto3,enum=cdc.ClosedBoundary_Mode" json:"mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClosedBoundary) Reset() {
	*x = ClosedBoundary{}
	mi := &file_cache_cdc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosedBoundary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosedBoundary) ProtoMessage() {}

func (x *ClosedBoundary) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosedBoundary.ProtoReflect.Descriptor instead.
func (*ClosedBoundary) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{2}
}

func (x *ClosedBoundary) GetCommittedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedBefore
	}
	return nil
}

func (x *ClosedBoundary) GetMode() ClosedBoundary_Mode {
	if x != nil {
		return x.Mode
	}
	return ClosedBoundary_MODE_UNSPECIFIED
}

// Full OLD/NEW column maps; also represents nested object values.
type RowImage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Fields        map[string]*ColumnValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowImage) Reset() {
	*x = RowImage{}
	mi := &file_cache_cdc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowImage) ProtoMessage() {}

func (x *RowImage) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowImage.ProtoReflect.Descriptor instead.
func (*RowImage) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{3}
}

func (x *RowImage) GetFields() map[string]*ColumnValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// SQL NULL is present null_value; a missing column has no map entry.
// Unlike google.protobuf.Value, numbers never pass through a double.
type ColumnValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ColumnValue_NullValue
	//	*ColumnValue_BoolValue
	//	*ColumnValue_StringValue
	//	*ColumnValue_NumberText
	//	*ColumnValue_ObjectValue
	//	*ColumnValue_ArrayValue
	Kind          isColumnValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnValue) Reset() {
	*x = ColumnValue{}
	mi := &file_cache_cdc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnValue) ProtoMessage() {}

func (x *ColumnValue) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnValue.ProtoReflect.Descriptor instead.
func (*ColumnValue) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnValue) GetKind() isColumnValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ColumnValue) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *ColumnValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *ColumnValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ColumnValue) GetNumberText() string {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_NumberText); ok {
			return x.NumberText
		}
	}
	return ""
}

func (x *ColumnValue) GetObjectValue() *RowImage {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *ColumnValue) GetArrayValue() *ValueList {
	if x != nil {
		if x, ok := x.Kind.(*ColumnValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

type isColumnValue_Kind interface {
	isColumnValue_Kind()
}

type ColumnValue_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type ColumnValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type ColumnValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ColumnValue_NumberText struct {
	NumberText string `protobuf:"bytes,4,opt,name=number_text,json=numberText,proto3,oneof"`
}

type ColumnValue_ObjectValue struct {
	ObjectValue *RowImage `protobuf:"bytes,5,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type ColumnValue_ArrayValue struct {
	ArrayValue *ValueList `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

func (*ColumnValue_NullValue) isColumnValue_Kind() {}

func (*ColumnValue_BoolValue) isColumnValue_Kind() {}

func (*ColumnValue_StringValue) isColumnValue_Kind() {}

func (*ColumnValue_NumberText) isColumnValue_Kind() {}

func (*ColumnValue_ObjectValue) isColumnValue_Kind() {}

func (*ColumnValue_ArrayValue) isColumnValue_Kind() {}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ColumnValue         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_cache_cdc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cdc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_cache_cdc_proto_rawDescGZIP(), []int{5}
}

func (x *ValueList) GetValues() []*ColumnValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cache_cdc_proto protoreflect.FileDescriptor

const file_cache_cdc_proto_rawDesc = "" +
	"\n" +
	"\x0fcache_cdc.proto\x12\x03cdc\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x0eCacheCdcRecord\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fsource_epoch\x18\x02 \x01(\tR\vsourceEpoch\x12(\n" +
	"\x06change\x18\x03 \x01(\v2\x0e.cdc.RowChangeH\x00R\x06change\x121\n" +
	"\bboundary\x18\x04 \x01(\v2\x13.cdc.ClosedBoundaryH\x00R\bboundaryB\x06\n" +
	"\x04body\"\xc2\x02\n" +
	"\tRowChange\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x126\n" +
	"\toperation\x18\x04 \x01(\x0e2\x18.cdc.RowChange.OperationR\toperation\x12%\n" +
	"\x06before\x18\x05 \x01(\v2\r.cdc.RowImageR\x06before\x12#\n" +
	"\x05after\x18\x06 \x01(\v2\r.cdc.RowImageR\x05after\"h\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_INSERT\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03\"\xd3\x01\n" +
	"\x0eClosedBoundary\x12E\n" +
	"\x10committed_before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0fcommittedBefore\x12,\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x18.cdc.ClosedBoundary.ModeR\x04mode\"L\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMODE_FENCED\x10\x01\x12\x1d\n" +
	"\x19MODE_MANAGED_INVALIDATION\x10\x02\"\x8a\x01\n" +
	"\bRowImage\x121\n" +
	"\x06fields\x18\x01 \x03(\v2\x19.cdc.RowImage.FieldsEntryR\x06fields\x1aK\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.cdc.ColumnValueR\x05value:\x028\x01\"\xa2\x02\n" +
	"\vColumnValue\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vnumber_text\x18\x04 \x01(\tH\x00R\n" +
	"numberText\x122\n" +
	"\fobject_value\x18\x05 \x01(\v2\r.cdc.RowImageH\x00R\vobjectValue\x121\n" +
	"\varray_value\x18\x06 \x01(\v2\x0e.cdc.ValueListH\x00R\n" +
	"arrayValueB\x06\n" +
	"\x04kind\"5\n" +
	"\tValueList\x12(\n" +
	"\x06values\x18\x01 \x03(\v2\x10.cdc.ColumnValueR\x06valuesBS\n" +
	"\x1fio.github.sleepkqq.rowrelay.cdcP\x01Z.github.com/sleepkqq/row-relay/internal/cdcwireb\x06proto3"

var (
	file_cache_cdc_proto_rawDescOnce sync.Once
	file_cache_cdc_proto_rawDescData []byte
)

func file_cache_cdc_proto_rawDescGZIP() []byte {
	file_cache_cdc_proto_rawDescOnce.Do(func() {
		file_cache_cdc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_cdc_proto_rawDesc), len(file_cache_cdc_proto_rawDesc)))
	})
	return file_cache_cdc_proto_rawDescData
}

var file_cache_cdc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cache_cdc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cache_cdc_proto_goTypes = []any{
	(RowChange_Operation)(0),      // 0: cdc.RowChange.Operation
	(ClosedBoundary_Mode)(0),      // 1: cdc.ClosedBoundary.Mode
	(*CacheCdcRecord)(nil),        // 2: cdc.CacheCdcRecord
	(*RowChange)(nil),             // 3: cdc.RowChange
	(*ClosedBoundary)(nil),        // 4: cdc.ClosedBoundary
	(*RowImage)(nil),              // 5: cdc.RowImage
	(*ColumnValue)(nil),           // 6: cdc.ColumnValue
	(*ValueList)(nil),             // 7: cdc.ValueList
	nil,                           // 8: cdc.RowImage.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(structpb.NullValue)(0),       // 10: google.protobuf.NullValue
}
var file_cache_cdc_proto_depIdxs = []int32{
	3,  // 0: cdc.CacheCdcRecord.change:type_name -> cdc.RowChange
	4,  // 1: cdc.CacheCdcRecord.boundary:type_name -> cdc.ClosedBoundary
	0,  // 2: cdc.RowChange.operation:type_name -> cdc.RowChange.Operation
	5,  // 3: cdc.RowChange.before:type_name -> cdc.RowImage
	5,  // 4: cdc.RowChange.after:type_name -> cdc.RowImage
	9,  // 5: cdc.ClosedBoundary.committed_before:type_name -> google.protobuf.Timestamp
	1,  // 6: cdc.ClosedBoundary.mode:type_name -> cdc.ClosedBoundary.Mode
	8,  // 7: cdc.RowImage.fields:type_name -> cdc.RowImage.FieldsEntry
	10, // 8: cdc.ColumnValue.null_value:type_name -> google.protobuf.NullValue
	5,  // 9: cdc.ColumnValue.object_value:type_name -> cdc.RowImage
	7,  // 10: cdc.ColumnValue.array_value:type_name -> cdc.ValueList
	6,  // 11: cdc.ValueList.values:type_name -> cdc.ColumnValue
	6,  // 12: cdc.RowImage.FieldsEntry.value:type_name -> cdc.ColumnValue
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cache_cdc_proto_init() }
func file_cache_cdc_proto_init() {
	if File_cache_cdc_proto != nil {
		return
	}
	file_cache_cdc_proto_msgTypes[0].OneofWrappers = []any{
		(*CacheCdcRecord_Change)(nil),
		(*CacheCdcRecord_Boundary)(nil),
	}
	file_cache_cdc_proto_msgTypes[4].OneofWrappers = []any{
		(*ColumnValue_NullValue)(nil),
		(*ColumnValue_BoolValue)(nil),
		(*ColumnValue_StringValue)(nil),
		(*ColumnValue_NumberText)(nil),
		(*ColumnValue_ObjectValue)(nil),
		(*ColumnValue_ArrayValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_cdc_proto_rawDesc), len(file_cache_cdc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cache_cdc_proto_goTypes,
		DependencyIndexes: file_cache_cdc_proto_depIdxs,
		EnumInfos:         file_cache_cdc_proto_enumTypes,
		MessageInfos:      file_cache_cdc_proto_msgTypes,
	}.Build()
	File_cache_cdc_proto = out.File
	file_cache_cdc_proto_goTypes = nil
	file_cache_cdc_proto_depIdxs = nil
}
